FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source (will be overridden by volume mount)
COPY . .

EXPOSE 5173
# Injecte la variable avant le build
ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}

# Start Vite dev server
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]