# Dockerfile for email-service
FROM node:20

# Set working directory inside the container
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the entire src folder
COPY ./src ./src

# Start the server
CMD ["node", "src/server.js"]
